"""add ML fields to schemes

Revision ID: 4276e1fc3948
Revises: 66490b25cc19
Create Date: 2026-08-08 18:07:29.803407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4276e1fc3948'
down_revision: Union[str, Sequence[str], None] = '66490b25cc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Nullable fields for existing scheme records
    op.add_column(
        "schemes",
        sa.Column(
            "income_limit",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "minimum_age",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "maximum_age",
            sa.Integer(),
            nullable=True,
        ),
    )

    # Boolean fields with safe defaults for existing records
    op.add_column(
        "schemes",
        sa.Column(
            "requires_land",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "requires_bpl",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "disability_priority",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # JSON fields with empty-list defaults for existing records
    op.add_column(
        "schemes",
        sa.Column(
            "target_occupations",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "preferred_employment",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )

    op.add_column(
        "schemes",
        sa.Column(
            "preferred_education",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'preferred_education')
    op.drop_column('schemes', 'preferred_employment')
    op.drop_column('schemes', 'target_occupations')
    op.drop_column('schemes', 'disability_priority')
    op.drop_column('schemes', 'requires_bpl')
    op.drop_column('schemes', 'requires_land')
    op.drop_column('schemes', 'maximum_age')
    op.drop_column('schemes', 'minimum_age')
    op.drop_column('schemes', 'income_limit')
    # ### end Alembic commands ###
