"""add_citizen_profile_table

Revision ID: 66490b25cc19
Revises: 03950369be93
Create Date: 2026-07-30 23:38:36.085822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66490b25cc19'
down_revision: Union[str, Sequence[str], None] = '03950369be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('education_level', sa.Enum('SSLC', 'Plus Two', 'Diploma', 'UG', 'PG', 'PhD', name='educationlevel'), nullable=False),
    sa.Column('employment_status', sa.Enum('Student', 'Employed', 'Self Employed', 'Unemployed', 'Retired', name='employmentstatus'), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bpl_card', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('General', 'OBC', 'SC', 'ST', 'EWS', name='category'), nullable=False),
    sa.Column('disability_status', sa.Boolean(), nullable=False),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='maritalstatus'), nullable=False),
    sa.Column('land_holding', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_profiles_id'), 'citizen_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_citizen_profiles_user_id'), 'citizen_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_profiles_user_id'), table_name='citizen_profiles')
    op.drop_index(op.f('ix_citizen_profiles_id'), table_name='citizen_profiles')
    op.drop_table('citizen_profiles')
    # ### end Alembic commands ###
