import {
  Brain,
  RefreshCw,
  Sparkles,
  Users,
} from "lucide-react";
import { useEffect, useState } from "react";

import {
  getAdminAIRecommendations,
  type AdminAIRecommendationsResponse,
} from "../../api/admin";

import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { CardSkeleton } from "../../components/ui/Skeleton";

export function AdminAIRecommendations() {
  const [data, setData] =
    useState<AdminAIRecommendationsResponse | null>(
      null,
    );

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState("");

  async function loadRecommendations() {
    try {
      setLoading(true);
      setError("");

      const result =
        await getAdminAIRecommendations();

      setData(result);
    } catch (err) {
      console.error(err);

      setError(
        "Unable to load AI recommendation analytics.",
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadRecommendations();
  }, []);

  return (
    <div className="space-y-8">
      {/* HEADER */}

      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-primary">
            Administration
          </p>

          <h1 className="mt-2 text-2xl font-semibold text-app-foreground">
            AI Recommendations
          </h1>

          <p className="mt-1 text-sm text-app-muted">
            Monitor AI-powered government scheme
            recommendations across citizen profiles.
          </p>
        </div>

        <Button
          variant="secondary"
          icon={
            <RefreshCw className="h-4 w-4" />
          }
          onClick={() =>
            void loadRecommendations()
          }
          disabled={loading}
        >
          Refresh
        </Button>
      </div>

      {/* ERROR */}

      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3">
          <p className="text-sm text-app-danger">
            {error}
          </p>
        </div>
      )}

      {/* LOADING */}

      {loading && (
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
        </div>
      )}

      {/* STATISTICS */}

      {!loading && data && (
        <>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <Card>
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-app-muted">
                    Citizens Evaluated
                  </p>

                  <p className="mt-3 text-3xl font-semibold text-app-foreground">
                    {data.statistics.citizens_evaluated}
                  </p>

                  <p className="mt-1 text-xs text-app-muted">
                    Active citizens with profiles
                  </p>
                </div>

                <div className="rounded-lg bg-brand-primary/10 p-3">
                  <Users className="h-5 w-5 text-brand-primary" />
                </div>
              </div>
            </Card>

            <Card>
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-app-muted">
                    Recommendations
                  </p>

                  <p className="mt-3 text-3xl font-semibold text-app-foreground">
                    {data.statistics.total_recommendations}
                  </p>

                  <p className="mt-1 text-xs text-app-muted">
                    Generated by AI pipeline
                  </p>
                </div>

                <div className="rounded-lg bg-amber-50 p-3">
                  <Brain className="h-5 w-5 text-amber-600" />
                </div>
              </div>
            </Card>

            <Card>
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-app-muted">
                    Average AI Confidence
                  </p>

                  <p className="mt-3 text-3xl font-semibold text-app-foreground">
                    {data.statistics.average_ai_confidence}%
                  </p>

                  <p className="mt-1 text-xs text-app-muted">
                    Across generated recommendations
                  </p>
                </div>

                <div className="rounded-lg bg-green-50 p-3">
                  <Sparkles className="h-5 w-5 text-green-600" />
                </div>
              </div>
            </Card>

            <Card>
              <div className="flex items-start justify-between">
                <div>
                  <p className="text-sm text-app-muted">
                    Schemes Recommended
                  </p>

                  <p className="mt-3 text-3xl font-semibold text-app-foreground">
                    {data.statistics.schemes_recommended}
                  </p>

                  <p className="mt-1 text-xs text-app-muted">
                    Unique schemes recommended
                  </p>
                </div>

                <div className="rounded-lg bg-blue-50 p-3">
                  <Brain className="h-5 w-5 text-blue-600" />
                </div>
              </div>
            </Card>
          </div>

          {/* TOP SCHEMES */}

          <Card className="overflow-hidden p-0">
            <div className="border-b border-app-border px-6 py-5">
              <h2 className="text-lg font-semibold text-app-foreground">
                Top Recommended Schemes
              </h2>

              <p className="mt-1 text-sm text-app-muted">
                Schemes most frequently recommended
                by the AI recommendation pipeline.
              </p>
            </div>

            {data.top_schemes.length === 0 ? (
              <div className="px-6 py-10 text-center">
                <p className="text-sm text-app-muted">
                  No AI recommendations available.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full min-w-[700px] text-left">
                  <thead className="border-b border-app-border bg-app-background">
                    <tr>
                      <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-app-muted">
                        Scheme
                      </th>

                      <th className="px-6 py-3 text-xs font-semibold uppercase tracking-wider text-app-muted">
                        Category
                      </th>

                      <th className="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-app-muted">
                        Recommendations
                      </th>

                      <th className="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-app-muted">
                        Avg. Confidence
                      </th>
                    </tr>
                  </thead>

                  <tbody className="divide-y divide-app-border">
                    {data.top_schemes.map(
                      (scheme) => (
                        <tr
                          key={scheme.scheme_id}
                          className="transition hover:bg-app-background/60"
                        >
                          <td className="px-6 py-4">
                            <p className="font-medium text-app-foreground">
                              {scheme.scheme_name}
                            </p>
                          </td>

                          <td className="px-6 py-4 text-sm text-app-muted">
                            {scheme.category}
                          </td>

                          <td className="px-6 py-4 text-right text-sm font-semibold text-app-foreground">
                            {scheme.recommendation_count}
                          </td>

                          <td className="px-6 py-4 text-right">
                            <span className="font-semibold text-app-foreground">
                              {
                                scheme.average_ai_confidence
                              }
                              %
                            </span>
                          </td>
                        </tr>
                      ),
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </Card>
        </>
      )}
    </div>
  );
}